### ISSUE TITLE
get range of matching group in the string

### ISSUE THREAD

**Issue by sagarrakshe** [slevithan/xregexp#100]
**String**: `This is my sample string`
**Regex**: `(sample)`

After testing the string against the regex, I get the matching group as `sample`. How do I get the range (*start, end index*) of the matching group in the string?
In this case the range for `sample` would be **11-16**

**Comment by slevithan** [comment]
Positions for the overall match are easy:

```
var result = /x/.exec(str);
// assuming a match was found...
result.index; // start pos
result.index + result[0].length; // end pos
```

Unfortunately, JavaScript (and therefore XRegExp by extension) does not provide any features to determine this accurately for subcaptures.

In some cases, the start and end position of subcaptures might only partially be within the overall match, or not at all. Consider a case like `/.(?=.*(.)$)/`.

`XRegExp.matchRecursive` offers something similiar-ish to this, when using the `valueNames` option. E.g.:

```
var str = 'Here is <div> <div>an</div></div> example';
var result = XRegExp.matchRecursive(str, '<div\\s*>', '</div>', 'gi', {
    valueNames: ['between', 'left', 'match', 'right']
});
/* -> [
{name: 'between', value: 'Here is ',       start: 0,  end: 8},
{name: 'left',    value: '<div>',          start: 8,  end: 13},
{name: 'match',   value: ' <div>an</div>', start: 13, end: 27},
{name: 'right',   value: '</div>',         start: 27, end: 33},
{name: 'between', value: ' example',       start: 33, end: 41}
] */
```
