### ISSUE TITLE
Where is the version 3 documentation?

### ISSUE THREAD

**Issue by gajus** [slevithan/xregexp#101]

**Comment by slevithan** [comment]
There is a complete list of changes to date in v3.0.0 at https://github.com/slevithan/xregexp/wiki/Roadmap . When v3 final is released I will update all the documentation on xregexp.com, using the inline code comments, etc.

**Comment by slevithan** [comment]
Note that http://xregexp.com/ was updated with v3.0.0 documentation earlier this week.
