### ISSUE TITLE
Document astral symbol support

### ISSUE THREAD

**Issue by mathiasbynens** [slevithan/xregexp#105]
http://xregexp.com/flags/ doesn’t mention the `A` flag.

(Perhaps [the Unicode add-on docs](http://xregexp.com/plugins/) could mention it as well.)

**Comment by mathiasbynens** [comment]
Also, http://xregexp.com/plugins/ still links to v2.0.0 on the CDN.

**Comment by slevithan** [comment]
None of xregexp.com has been updated yet for v3.0.0. Working on it now, and planning to update tonight.

**Comment by mathiasbynens** [comment]
Thanks!

Btw, have you considered putting the website’s source code on GitHub? That way other people could help you out.

**Comment by slevithan** [comment]
I'd love to but at the moment I'd be embarrassed to. It needs a lot of cleanup.

**Comment by slevithan** [comment]
Okay, xregexp.com should now be fully up to date! Feel free to file new issues if you notice any problems.

I'd also be happy to provide the xregexp.com source code privately to anyone who's interested in helping to clean it up, move it to GitHub, and perhaps start generating it automatically.
