### ISSUE TITLE
Stop supporting pre-ES5 browsers

### ISSUE THREAD

**Issue by slevithan** [slevithan/xregexp#108]
Pre-ES5 browsers include e.g. IE 8 and earlier. Right now XRegExp still supports ancient browsers like IE 5.5, Firefox 1.5, Chrome 1, and Safari 3, which is totally unnecessary. But there's not much benefit to dropping support for these browsers until XRegExp can rely on ES5.

Some things to do after dropping pre-ES5 support:
- Generally take advantage of any ES5 features.
  - Use character indexing on strings instead of `charAt`, use `Array.prototype.indexOf`, etc.
- Possibly kill the entire custom split implementation and make `XRegExp.split` just defer to `String.prototype.split`, if there are few enough edge cases that ES5 browsers get wrong.
- Possibly kill handling for inconsistencies related to nonparticipating capturing groups (search for `nonparticipating` in code), if ES5 browsers generally get this right.
- Possibly kill the `[^]` and `[]` transforms if all ES5 browsers get this right.

**Comment by josephfrazier** [comment]
On a related note, would you be interested in using [babelify](https://github.com/babel/babelify) to compile ES2015+ code down to ES5? This would allow a [variety of syntax upgrades](https://babeljs.io/learn-es2015/) to the files in `src/`, while preserving correct behavior of `xregexp-all.js` in all ES5+ browsers.

One way of doing this is to install `babelify` and `babel-preset-es2015` as `devDependencies`, then change the `build` script to

```sh
browserify src/index.js --standalone XRegExp --transform [ babelify --presets [ es2015 ] ] > xregexp-all.js
```

**Comment by slevithan** [comment]
@josephfrazier Yes I'd be happy happy to move to ES2015+ code and compile down to ES5, if you're willing to set it up! :D Before doing that I'd want to get out a minor update, since dropping support for pre-ES5 browsers should be a v4.0.0 breaking change.

It would be nice to also have ES5 versions of all the individual modules, for people who don't want to use `xregexp-all.js`. I guess those could go in a new `dist` directory or similar, and `xregexp-all.js` should probably move in there as well.

**Comment by josephfrazier** [comment]
Great to hear, thanks! Given the current arrangement of [milestones](https://github.com/slevithan/xregexp/milestones), I assume these changes will have to wait until https://github.com/slevithan/xregexp/issues/45 is resolved and v3.2.0 is released? Since the compiled `xregexp-all.js` is currently stored in the repo, making a pull request for Babel now means that it would cause a merge conflict with any other changes that need to happen first.

**Comment by slevithan** [comment]
No, #45 can move to v4 or a post-v4 release. That also gives more time to see where the https://github.com/tc39/proposal-regexp-named-groups proposal goes.

However, I would still like to release a v3.2.0 with all the changes that have landed to date. No changes are blocking this, although I might make some tweaks and or accept PRs before then. I'll try to publish v3.2.0 (and update xregexp.com) this weekend, in order to unblock progress.

**Comment by josephfrazier** [comment]
Oh, that makes sense to wait on the TC39 proposal before moving forward on #45. I realized that I can open a PR that simply adds Babel to the build pipeline, but doesn't change `xregexp-all.js` or any of the `src/` files, just to get the ball rolling and show how it might look, so I might go ahead and do that. It may even be possible to get some backwards-compatible changes in v3.2.0, but we'll see.

**Comment by firatsarlar** [comment]
It would be nice to convert old code, which supports old browsers, to a migration script ( As what Jquery did with Jquery Migrate ) .. Old efforts may have some use cases .

**Comment by josephfrazier** [comment]
I think this one is technically complete, now that the following have been merged:

* https://github.com/slevithan/xregexp/pull/174
* https://github.com/slevithan/xregexp/pull/186
* https://github.com/slevithan/xregexp/pull/193
* https://github.com/slevithan/xregexp/pull/194

Of course, some of the follow-up items have yet to be done:

> Some things to do after dropping pre-ES5 support:
> - Generally take advantage of any ES5 features.
>   - Use character indexing on strings instead of `charAt`, use `Array.prototype.indexOf`, etc.
> - Possibly kill the entire custom split implementation and make `XRegExp.split` just defer to `String.prototype.split`, if there are few enough edge cases that ES5 browsers get wrong.
> - Possibly kill handling for inconsistencies related to nonparticipating capturing groups (search for `nonparticipating` in code), if ES5 browsers generally get this right.
> - Possibly kill the `[^]` and `[]` transforms if all ES5 browsers get this right.
