### ISSUE TITLE
`(?:)*` should not be a syntax error

### ISSUE THREAD

**Issue by slevithan** [slevithan/xregexp#112]
Reported by Jan Goyvaerts over email. As of XRegExp 3.0.0, a leading `(?:)*` is a syntax error. This is due to the cleanup at [xregexp.js#L614-L615](https://github.com/slevithan/xregexp/blob/7563982966f8606bfe79c3698efd4e355e2d775e/src/xregexp.js#L614-L615).

`(?:)*` serves no purpose, so this is a low-priority bug. However, it was an unintended change in XRegExp 3.0.0.

Note that `XRegExp.build` has special handling for leading `^` and trailing `$` that relies on XRegExp's cleanup of leading and trailing empty `(?:)` groups, since various XRegExp syntax tokens and flags inject `(?:)` to ensure that preceding and following tokens are kept independent from each other.

A possible fix for this is to strip any immediately following quantifier along with removed empty `(?:)` groups. Alternatively, XRegExp could be more careful about where `(?:)` is injected, or not rely on cleanup of empty noncapturing groups.

**Comment by jfahrenkrug** [comment]
I've created a fix for it here: https://github.com/slevithan/xregexp/pull/116
