### ISSUE TITLE
When used with webpack require('xregexp').XRegExp doesn't work anymore

### ISSUE THREAD

**Issue by jfahrenkrug** [slevithan/xregexp#115]
I run unit tests with node.js and I have an require('xregexp').XRegExp import. That works fine. But when I build with webpack, XRegExp is undefined.

**Comment by MadLittleMods** [comment]
Hey @jfahrenkrug,

It is exported directly(no need to try to get a property):

```js
var xregexp = require('xregexp');
var fooTest1 = xregexp.exec('foobar', xregexp('^foo(.*)', 'i'));
console.log(fooTest1);
```

**Comment by jfahrenkrug** [comment]
Right, but interestingly the `.XRegExp` works under node, but not when compiled with webpack. This seems to be the cause: https://github.com/slevithan/xregexp/blob/master/xregexp-all.js#L18

For consistency's sake, it would be nice if either `.XRegExp` is always defined or never defined, no matter what environment you use.

**Comment by slevithan** [comment]
@jfahrenkrug This is likely due to #122 which changed how xregexp-all.js is built. After the next release, the `.XRegExp` property should not be available anywhere. If it seems important to keep it, let me know.

**Comment by jfahrenkrug** [comment]
@slevithan Excellent! Thank you very much!
