### ISSUE TITLE
Capture group fill on repeat

### ISSUE THREAD

**Issue by MadLittleMods** [slevithan/xregexp#117]
With native JavaScript and `xregexp` currently, capture groups will get clobbered on successive repeat passes.

Other implementations ignore undefined capture groups on repeated passes and just keep filling.

`(?:(foo|bar)|(baz|qux))+`
 - XRegExp: https://jsfiddle.net/MadLittleMods/3gLgumd3/
 - JavaScript: https://regex101.com/r/vT5oC0/1#javascript
 - PCRE: https://regex101.com/r/vT5oC0/1#pcre

Input | [JavaScript](https://regex101.com/r/vT5oC0/1#javascript) | [PCRE & Python](https://regex101.com/r/vT5oC0/1#pcre)
------ | -------------- | -----------------------
`foobaz` | 2. `baz` |  1. `foo` 2. `baz`
`bazfoo` | 1. `foo` | 1. `foo`  2. `baz`

---

I could see this being a new flag to enable either behavior(ignore, fill undefined/empty).

**Comment by slevithan** [comment]
I agree this would be useful, but due to XRegExp's core architecture (it transpiles to native JS regex syntax) this is not possible. :'( It would be great if future versions of JS changed this behavior though.
