### ISSUE TITLE
Does XRegExp support non-capturing groups?

### ISSUE THREAD

**Issue by retorquere** [slevithan/xregexp#119]
I tried `(?:...)` but they seem to capture.

**Comment by slevithan** [comment]
Yes, XRegExp supports all JavaScript regex syntax including non-capturing groups (which don't capture). Can you show an example of what you're trying to do?

**Comment by retorquere** [comment]
I tried this:

```
var re = new XRegExp("(?:^|[^\\p{N}\\p{L}])([\\p{L}\\p{N}]*\\p{Lu}[\\p{L}\\p{N}]*)", 'gx');

var str = "Wisdom: A Metaheuristic (pragmatic) to <i>Orchestrate</i> Mind and Virtue toward Excellence.";

str = XRegExp.replace(str, re, function(match) {
  var arg, i, len;
  console.log('-----');
  for (i = 0, len = arguments.length; i < len; i++) {
    arg = arguments[i];
    console.log(JSON.stringify(arg));
  }
  return match;
});
```
and the first argument to the replaces seems to include the non-capturing group. I'm trying to emulate `\b`.

**Comment by retorquere** [comment]
Ah, wait... non capturing only means it doesn't show up in the capture groups, it's not in itself an empty match like `\b`. Right?

**Comment by retorquere** [comment]
I've just been informed I should be using lookbehind, but that JS regexes don't support it. Shame.

**Comment by slevithan** [comment]
https://gist.github.com/slevithan/2387872 might be of interest.

**Comment by retorquere** [comment]
Thanks for the tip! I've looked it through, but it doesn't seem to support regexes with alternates; mine is actually:

```
(
          # word with embedded punctuation
          ((?<boundary1>^|[^'\\p{N}\\p{L}])   (?<word1>[\\p{L}\\p{N}]+'[\\p{L}\\p{N}]+))
          |
          ((?<boundary2>^|[^-\\p{N}\\p{L}])   (?<word2>[\\p{L}\\p{N}]+[-\\p{L}\\p{N}]+[\\p{L}\\p{N}]))

          |
          # simple word
          ((?<boundary3>^|[^\\p{N}\\p{L}])    (?<word3>[\\p{L}\\p{N}]*\\p{Lu}[\\p{L}\\p{N}]*))
        )
```

where I'd love the `boundary` groups to be lookbehinds
