### ISSUE TITLE
Alternatives broken

### ISSUE THREAD

**Issue by drdevnull** [slevithan/xregexp#125]
When using (n|m) type alternative matching, I'm getting unwanted behaviour. 

I cannot find any documentation about how to use alternatives...

Try: 
var gramRegex = XRegExp('(?<grams> (grams|gr) )', 'igx');
var match = XRegExp.exec('20 grams', gramRegex);
console.log(match);

**Comment by slevithan** [comment]
@drdevnull Alternatives in XRegExp work just like alternatives in native JavaScript regexes. There seems to be a character missing in your example regex though (`(? ...)` is not valid syntax) so I can't try it. What problem are you encountering?

**Comment by drdevnull** [comment]
thanks for the message. In pure javascript it also works without the ? character...

from http://www.w3schools.com/js/js_regexp.asp:
(x|y) 	Find any of the alternatives separated with |

Try:
http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_regexp_boundary

with:
var str = "Visit W3Schools"; 
var patt1 = /(\bW3|\bVi)/g;

**Comment by drdevnull** [comment]
btw - it looks like the example I posted is broken. I might have made an error when posting the problem. I'll retry the native regexes in application which currently work with XRegExp.
