### ISSUE TITLE
XRegExp and ES2015 RegExp subclassing support

### ISSUE THREAD

**Issue by littledan** [slevithan/xregexp#127]
ES2015 makes some changes to JavaScript RegExps which are meant to help subclassing. These mean that overriding the `exec` method (e.g., by monkey-patching `RegExp.prototype`) results in methods like `String.prototype.replace` calling out to that new `exec`.

I'm working on implementing ES2015 in V8. In the past, we've implemented an optimization where `String.prototype.replace` calls out to the underlying Irregexp engine only once, and this trick gets a pretty sizable performance win. A naive strategy for optimizing ES2015 RegExps would be to check whether `RegExp.prototype` has been messed with, and implement our optimization when it hasn't been.

But it seems like XRegExp wouldn't hit this fast path when it's used in the mode where it's installed directly onto `RegExp.prototype` — the new `String.prototype.replace` method calls the native `String.prototype.replace` method, but ultimately, ES2015 semantics require implementations to call out to XRegExp's `exec` method, so the optimization would be invalid. This might mean something like a ~20% perf regression on XRegExp vs native RegExps. (Sorry, I don't have real perf numbers yet.)

I see a few things that could be done to mitigate this issue:
- Do people actually use `natives: true` that often? Maybe we could document the performance hazard and encourage them not to. (Note, this hazard isn't present in current browsers, but it may in the near future.)
- Looks like XRegExp only needs to change `exec` to support browser workarounds and named capture groups (anything else?). Native named capture groups are actually on the way, having been discussed in TC39 and currently sitting at Stage 0. Maybe once that's all in, XRegExp could refrain from monkey-patching `exec` if it feature-tests positive for this feature.
- If all else fails, and this seems to be an important performance regression, we could try to push again for a spec change along the lines of [what I proposed](https://docs.google.com/presentation/d/19LyObVMn7jKt9qCPA_bpm5TDLqk1ruDcYCAwAScM-vE/edit)  at the November 2015 TC39 meeting to not call out to the underlying `exec` method.

**Comment by mathiasbynens** [comment]
I’d be in favor of removing `natives: true` support altogether in the next major XRegExp release.

If not, feature-testing before monkey-patching sounds good.

**Comment by slevithan** [comment]
I'd also be in favor removing `natives: true` support altogether in the next major XRegExp release.

**Comment by littledan** [comment]
Sounds good to me!

**Comment by slevithan** [comment]
See also #89 which discussed removing `natives: true`.

**Comment by slevithan** [comment]
Removing `natives: true` is covered by #89 so closing this one.
