### ISSUE TITLE
Create xregexp-all.js from gulp

### ISSUE THREAD

**Issue by AndorLundgren** [slevithan/xregexp#128]
I may need help to understand how to include this in browser.

According to manual and examples I should include:
```
<script src="src/xregexp.js"></script>
<script src="src/addons/unicode-base.js"></script>
```
or load all bundles with xregexp-all.js.

When i include xregexp.js it complains: on row module.exports = XRegExp;
I have no module..

When downloading with npm, I do not get the file xregexp-all.js

Is there a simple way to create the xregexp-all.js file from xregexp.js and addons with help of gulp and browserify?

**Comment by slevithan** [comment]
Ack! Will need to fix this by including builds of the individual scripts that run in browsers, and or update `README`. CC @alexgorbatchev who submitted the related change for this.

`xregexp-all.js` will run in a browser. I've been using that in my browser tests. You can create `xregexp-all.js` using `npm run build` or `browserify src/index.js --standalone XRegExp > xregexp-all.js`.

**Comment by AndorLundgren** [comment]
Thank you very much for the answer. New to browserify and had problems to understand how to wrap everything in my gulpfile. By using standalone parameter the file was created and could be used by my non module js.

**Comment by slevithan** [comment]
@alexgorbatchev any ideas on how to build standalone copies of all the addons that will work with browsers? Would be nice to include standalone copies of `xregexp.js` and each of the individual addons as separate files inside a new root `dist` directory.

**Comment by slevithan** [comment]
Closing since the documentation has been updated.
