### ISSUE TITLE
Slow x flag with newlines and spaces

### ISSUE THREAD

**Issue by lencioni** [slevithan/xregexp#129]
I am using xregexp 3.1.0 and node 5.1.0. 

With the following JS (in a file called `test.js`):

```js
const xRegExp = require('xregexp');
const r = xRegExp(`
                          #
                          #
  `, 'x'
);
```

Node takes 12s to execute:

```sh
> time node test.js
node test.js  12.29s user 0.05s system 99% cpu 12.394 total
```

But the following code:

```js
const xRegExp = require('xregexp');
const r = xRegExp(`
      #
      #
  `, 'x'
);
```

takes much less time.

```sh
> time node test.js
node test.js  0.11s user 0.01s system 96% cpu 0.129 total
```

What up with that?

![whatupwiththat](https://cloud.githubusercontent.com/assets/195534/14008604/0efc3ad8-f140-11e5-86e4-259924435389.gif)

**Comment by lencioni** [comment]
I added something like this to the perf test suite:

```js
    (function() {
        var configs = [
            {
                name: 'Constructor with comments and lots of spaces',
                pattern: '\n                       # comment\n                       # comment\n'
            },
        ];

        configs.forEach(function(config) {
            suites.push(Benchmark.Suite(config.name)
                .add('XRegExp with pattern cache flush', function() {
                    XRegExp(config.pattern, 'x');
                    XRegExp.cache.flush('patterns');
                })
                .add('XRegExp', function() {
                    XRegExp(config.pattern, 'x');
                })
                .add('XRegExp.cache', function() {
                    XRegExp.cache(config.pattern, 'x');
                })
                .add('RegExp', function() {
                    new RegExp(config.pattern, 'x');
                })
            );
        });
    }());
```

and in Chrome Version 49.0.2623.87 (64-bit) on a 2015 Macbook Pro, I got the following result:

```
Constructor with comments and lots of spaces:
XRegExp with pattern cache flush x 0.26 ops/sec ±0.92% (5 runs sampled)
XRegExp x 536,012 ops/sec ±2.70% (90 runs sampled)
XRegExp.cache x 49,597,118 ops/sec ±1.15% (91 runs sampled)
RegExp: 
Fastest is XRegExp.cache
```

**Comment by slevithan** [comment]
Yikes, that's terrible--thanks for reporting. This should be pretty straightforward to fix though. Sounds like a case of runaway backtracking in one of the regexes that XRegExp is using to deal with the `x` flag.

**Comment by slevithan** [comment]
With the linked commit, performance for the test case in your original report improved from 10433.590ms to 0.132ms in Chrome 49.

I didn't add a test to the performance suite because this was strictly a bug and there shouldn't be much reason for this to change from version to version, compared to other example patterns.

Thanks again for reporting @lencioni!

**Comment by lencioni** [comment]
Thanks so much for the quick fix and release! :dancer:

**Comment by slevithan** [comment]
Planning to release after making progress on #128.

**Comment by slevithan** [comment]
v3.1.1 has been published and includes this fix.
