### ISSUE TITLE
Cleaner Key Organization In Result for Matches

### ISSUE THREAD

**Issue by Magnitus-** [slevithan/xregexp#136]
Hi,

first of all, thanks for this great library. I think it's awesome.

When you do a match as per the introductory example and look at the result object, in addition to the keys mapping named groups in the regex, there are the following keys: [ '0', '1', '2', 'index', 'input'].

Without necessarily advocating that the info contained in those keys be removed from results, wouldn't it be cleaner if they were more strictly separated from results (ie, what happens if you have a named group called 'index' or 'input' or if you validate the resulting object with a library like joi that doesn't allow unforeseen keys by default?)?

Perhaps that could be accomplished by including a key like 'groups' in the match object which would contain a sub-object that has all the values of the named groups...

My humble opinion.

Cheers.

Eric

**Comment by slevithan** [comment]
Thanks for the feedback. Yes, I agree that it would be cleaner if named backreferences and other properties weren't mixed. There's actually a longstanding issue open for this at #45 -- there's a lot to read there but you'll see in the end that I support switching this in a breaking change, and adding a toggleable option for this earlier than that. In the meantime, there is a workaround by using the undocumented `<xregexp>.xregexp.captureNames`.

**Comment by Magnitus-** [comment]
I see, my apologies for missing the other issue and making a duplicate.

I thank you for the feedback and info concerning this issue. I will look into the workaround.
