### ISSUE TITLE
Invalid duplicate regex flag

### ISSUE THREAD

**Issue by Unrealomega** [slevithan/xregexp#138]
When attempting to create a XRegExp object, it throws a Syntax Error stating there is a "Invalid duplicate regex flag". Regardless if I use my own syntax or the usage example's regex, it throws this; I've tried single regex elements by themselves and they fail as well. 

I'm using node.js.

```
D:\Projects\nodejs\discord_bot\node_modules\xregexp\src\xregexp.js:336`
        throw new SyntaxError('Invalid duplicate regex flag ' + flags);
        ^

SyntaxError: Invalid duplicate regex flag /d+/
    at prepareFlags (D:\Projects\nodejs\discord_bot\node_modules\xregexp\src\xre
gexp.js:336:15)
    at XRegExp (D:\Projects\nodejs\discord_bot\node_modules\xregexp\src\xregexp.
js:551:23)
    at parse (D:\Projects\nodejs\discord_bot\dice_roller.js:9:23)
    at Client.<anonymous> (D:\Projects\nodejs\discord_bot\base.js:12:30)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at WebSocket.websocket.onmessage (D:\Projects\nodejs\discord_bot\node_module
s\discord.js\lib\Client\InternalClient.js:90:15)
    at WebSocket.onMessage (D:\Projects\nodejs\discord_bot\node_modules\discord.
js\node_modules\ws\lib\WebSocket.js:442:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
```

**Comment by slevithan** [comment]
There isn't enough information here to debug. Note that XRegExp is distributed with tests. Are they all passing in your browser, as they are for me? Are you using v3.1.1 (the latest version)? What code are you actually running to create an XRegExp object?

XRegExp intentionally does not allow duplicate flags to be provided. E.g. the following will throw the error: `XRegExp("\\d+", "ii")`.

**Comment by Unrealomega** [comment]
I'm using it in straight node.js (Running the script with "node script.js"). Version is 3.1.1 and the code I'm using is this:
```var dice_regex = XRegExp('\\roll\s+(?<amt>\d+)?-d(?<size>\d+)')````

I've tried the example, though it still responds the same way:
```var dice_regex = XRegExp('(?<year>  [0-9]{4} ) -?  # year  \n' +
               '(?<month> [0-9]{2} ) -?  # month \n' +
               '(?<day>   [0-9]{2} )     # day     ', 'x')```

**Comment by slevithan** [comment]
Not enough information to go on here. If what you're saying is accurate and complete it would seem XRegExp shouldn't work at all. Are you able to get even more basic regexes to run with XRegExp?

Aside: Note that you're not escaping your backslashes in your `dice_regex` string. It should probably be ` XRegExp('\\\\roll\\s+(?<amt>\\d+)?-d(?<size>\\d+)')`.
