### ISSUE TITLE
After pull can not see xregexp-all.js

### ISSUE THREAD

**Issue by technobia** [slevithan/xregexp#139]
After I pulled your code. I don't see xregexp-all.js. Event I run with "slevithan/xregexp#63273f93d97dd7345b6cc57b59ae5d6213d29b8d". But I saw in github repository. So I there are any way to use 'xregexp-all.js' file without run build script?

Thanks you for help!

**Comment by kaiquewdev** [comment]
Of course: https://raw.githubusercontent.com/slevithan/xregexp/master/xregexp-all.js

**Comment by kaiquewdev** [comment]
Or just save your progress and clone again.
