### ISSUE TITLE
g flag does not seem to work

### ISSUE THREAD

**Issue by Rainforce15** [slevithan/xregexp#146]
When using the g flag, the result does appear as an array (as compared to the regular result), but only contains a single element with the first actual match.
When forEach is used, all matches are properly detected.

**Comment by mathiasbynens** [comment]
Please provide a code snippet that reproduces the issue.

**Comment by Rainforce15** [comment]
`var fileRegex = new XRegExp("\\/\\*\\*.*?@class (?<class>.*?)\\n.*?(?:(?<constructor>@constructor)\\n.*?)?(?:@extends (?<extends>.*?)\\n.*?)?\\*\\/", "gs");`

This is just for parsing some class dependencies in a file with YUIdoc comments like this:

```
        /**
         * @class test1
         * @constructor
         */

        /**
         * @class test2
         * @constructor
         * @extends test1
         */
```

expected result should be when running exec that an array containing both entries is returned, but 
` XRegExp.exec(data, fileRegex);`
only returns the same data as match - forEach on the other hand returns indeed each.

**Comment by slevithan** [comment]
That is not how `XRegExp.exec` (or the native `RegExp.prototype.exec`) works with flag `g`. With `RegExp.prototype.exec`, `g` doesn't change what kind of result is returned; rather it makes the match attempt use `RegExp.prototype.lastIndex` as its starting position. `XRegExp.exec` uses the provided `pos` argument to set the start position regardless of whether the provided regex uses flag `g`. See http://xregexp.com/api/#exec for details. For your use case, use `XRegExp.match` or `XRegExp.forEach`.

**Comment by Rainforce15** [comment]
thanks, I misunderstood the exec() description's "match array" (correct term though, just misguided expectations for its meaning)
