### ISSUE TITLE
[\0-\uFFFF] leads to invalid UTF-8 string after processing by UglifyJS

### ISSUE THREAD

**Issue by stefanbethke** [slevithan/xregexp#150]
In my application, I use Gulp to combine and minify the libs that I need. The resulting minified file is then imported into a content management system. The import tool complains that there is an invalid Unicode character U+FFFF in the import.  I traced it back to line 478 in xregexp-all.js.  I believe changing \uFFFF to \uFFFD avoid this error on import, and should provide the same functionality.

Alternatively, UglifyJS could be taught to no de-escape \uFFFF, like it does with a number of special characters already.

**Comment by mathiasbynens** [comment]
This is a bug with UglifyJS, not XRegExp.

**Comment by stefanbethke** [comment]
I fully agree, and after experimenting with replacing occurences of \uffff with \ufffd, the problem shifts to other sequences.

**Comment by stefanbethke** [comment]
I've added a pull request for UglifyJS: https://github.com/mishoo/UglifyJS2/pull/1311
