### ISSUE TITLE
XRegExp.test hangs on string with digits at the end

### ISSUE THREAD

**Issue by StreetStrider** [slevithan/xregexp#151]
Hello. Looks like our QA has digged a perfomance issue. I got regexp to determine multiple words:

```js
var XRegExp = require('xregexp')

var re = XRegExp.build(`^ {{word}} (\\s {{word}})* $`,
{
	word: XRegExp(`\\pL+ ([' -] \\pL+)* \\.?`, 'x')
},
'x')

// this works fine:
console.time('1')
console.log(re.test('Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin'))
console.timeEnd('1')

console.time('2')
// uncomment this and it'll hang the process
// console.log(re.test('Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin Admin 444'))
console.timeEnd('2')
```
As is an example, if string contains digits at the end of it, *looks* like engine goes to very huge cycle. I can't even wait for it to finish. And as this code is syncronous it cause one node to hang forever.
`node 4`, tested with `xregexp@3.1.1`.

I still wondering maybe something wrong with my regexp itself (so it creates very expensive computations by its nature), but I'm not sure. I'm expecting rather true or false, possible slowly, but not taking forever.

**Comment by slevithan** [comment]
Haven't verified, but this sounds like a case of [catastrophic backtracking](http://www.regular-expressions.info/catastrophic.html).

**Comment by StreetStrider** [comment]
@slevithan yes, it looks like bad backtracking, indeed there're nested quantifiers which can lead to bad performance. Thanks for the reading, it seemes that there can be a solution. I'll return with results shortly and close this ticket.

**Comment by StreetStrider** [comment]
@slevithan it looks like sparse regexp is not allowed inside character classes, please confirm.
If true the issue is in here: `[' -]`, I've removed space inside and issue vanishes.

**Comment by slevithan** [comment]
I'm not sure what you mean by sparse regexp, but that doesn't sound correct.

Your comment about removing the space from the allowed characters in the character class only further validates the idea that this is a case of catastrophic backtracking, given that space is the only character that is allowed to match in both your inner and outer loop.

From a cursory reading, it doesn't appear that including a space in the character class changes anything at all about what your pattern is able to match. So yeah, just removing it should be an easy fix here.

**Comment by StreetStrider** [comment]
@slevithan by sparse regexp I mean `x` modificator ("free-spacing and line comments" as in your readme). I use space in character class just only as "free-space" and not one to match against. My investigation showed that "free-space" is not allowed in character class.

**Comment by slevithan** [comment]
Ah, gotcha. Yes, that's correct. Like every other regex flavor that I know of except Java, in XRegExp the `x` flag does not cause whitespace within character classes to be ignored. Note that this is documented at <http://xregexp.com/flags/#extended>.

**Comment by StreetStrider** [comment]
@slevithan, good to know. Thanks again for help. :+1:
