### ISSUE TITLE
Upgrade to Unicode 9.0.0

### ISSUE THREAD

**Issue by slevithan** [slevithan/xregexp#171]
From <http://www.unicode.org/versions/Unicode9.0.0/>:

> Unicode 9.0 adds exactly 7,500 characters, for a total of 128,172 characters. These additions include six new scripts and 72 new emoji characters.

The categories, scripts, blocks, and properties addons will all need to be updated. Steps:

* Delete files in `tools/data/` for the old version (8.0.0).
* Update the Unicode version number in `tools/generate-unicode.sh`.
* Manually update the code points and ranges for the handful of properties in `tools/scripts/property-regex.py`, using data generatable from [UnicodeSet](http://unicode.org/cldr/utility/list-unicodeset.jsp) (see [comments here](https://github.com/slevithan/xregexp/issues/29#issuecomment-6534190)).
* Run `tools/generate-unicode.sh`.
* Use the generated data in `tools/output/` to update the Unicode addon JS files in `src/addons/`.

Also update the "Uses Unicode 8.0.0" comments in `README.md`, `unicode-blocks.js`, `unicode-categories.js`, `unicode-properties.js`, and `unicode-scripts.js`.

**Comment by mathiasbynens** [comment]
It might be worth considering rewriting the build scripts to consume the node-unicode-data packages, e.g. https://github.com/mathiasbynens/unicode-9.0.0, directly. This would greatly simplify things and could reduce the manual work required for such updates in the future.

**Comment by slevithan** [comment]
If nothing else, it might be easier to get the data for the handful of properties listed in `tools/scripts/property-regex.py` from https://github.com/mathiasbynens/unicode-9.0.0/tree/master/Binary_Property than from UnicodeSet.
