### ISSUE TITLE
Using xregexp - Critical dependencies ( This seems to be a pre-built javascript file )

### ISSUE THREAD

**Issue by Philin-Anton** [slevithan/xregexp#191]
Critical dependencies:
1:480-487 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/xregexp/xregexp-all.js 1:480-487

npm dependencies:
  "xregexp": "^3.2.0"
   "webpack": "^1.15.0",

**Comment by Philin-Anton** [comment]
Registered in the config
noParse: [
      new RegExp('node_modules/xregexp/xregexp-all.js')
    ]
not working.

**Comment by kaidjohnson** [comment]
try using "xregexp": "3.2.0-next"

this issue was addressed via https://github.com/slevithan/xregexp/pull/187 and https://github.com/slevithan/xregexp/pull/182
