### ISSUE TITLE
regex with look-behind

### ISSUE THREAD

**Issue by dportabella** [slevithan/xregexp#200]
you mention the following in your doc: http://xregexp.com/history/

> Fix: Include lookbehind prefixes (?<= and (?<! in list of native tokens, to avoid splitting up this prefix in any custom addons since some browsers have started supporting this natively.

I tried with Chrome, Firefox and Safari, and none of them support look-behind. Which browsers are you aware that support look-behind?

Also, are you aware of any regex library in javascript which supports look-behind?

such as:
```
re = /(?<!a)b+/g;
re.exec('ab abb bbbbb');

```

**Comment by slevithan** [comment]
I'm not certain, but I believe I was testing it with Chrome at the time. Perhaps they've removed support for it since, or moved it behind an experimental flag.

I don't recall JS regex libraries with lookbehind support.

**Comment by fghber** [comment]
Regex with look-behind work for me with the latest Chrome (v65).

```
(<script src="https://unpkg.com/xregexp/xregexp-all.js"></script>
<script>
var x = XRegExp('(?<=&lt;)(\\w*)(?=&gt;)?', 'g');
var arr = XRegExp.split('&lt;div&gt; div', x);
console.log(arr);)
```
