### ISSUE TITLE
globalize doesn't support named parameters

### ISSUE THREAD

**Issue by qpongo** [slevithan/xregexp#203]
## .globalize should support named parameters to be consistent with the rest of the module and with other Regex engines.

**Repro:**
```
const XRegExp = require('xregexp');

const regex = XRegExp('(?<x>a)(?<y>b+)');

const str = 'jabba the hut';

let m = XRegExp.exec(str, regex);
console.log(`m.x = ${m.x}; m[1] = ${m[1]}`);

const regexG = XRegExp.globalize(regex);

while (m = regexG.exec(str)) {
    console.log(`m.x = ${m.x}; m[1] = ${m[1]}`);
}

```
**Actual:**

> m.x = a; m[1] = a
m.x = undefined; m[1] = a

**Expected:**

> m.x = a; m[1] = a
m.x = a; m[1] = a

_I apologize for not taking the time to look at the source and see if there is a solution -- maybe I'll have time next week._

**Comment by slevithan** [comment]
`.globalize` does fully support named parameters. This is also tested for here: https://github.com/slevithan/xregexp/blob/a661cd3ebbaf9950f947c5b92039d7c565ce8a5b/tests/spec/s-xregexp-methods.js#L701-L705

The issue is that you are using `XRegExp.exec` with your nonglobalized regex, and the native `RegExp.prototype.exec` (which doesn't support named captures) with the globalized copy. Use `XRegExp.exec` with it and it should work (`while (m = XRegExp.exec(str, regexG))`).

**Comment by qpongo** [comment]
OK.  Changed as you suggested but that makes an infinite loop.

```
const regexG = XRegExp.globalize(regex);

while (m = XRegExp.exec(str, regexG)) {
    console.log(`m.x = ${m.x}; m[1] = ${m[1]}`);
}
```
**Actual:**
m.x = a; m[1] = a
m.x = a; m[1] = a
m.x = a; m[1] = a
m.x = a; m[1] = a
m.x = a; m[1] = a
...

The acceptance test test you have doesn't call it in a loop so it only gets the first match and doesn't show the indexes moving along.

Maybe my problem is with my understanding?  And that I'm expecting the interface to work differently?

I thought that regexG was a new globalized regex in my example.  Maybe my example wasn't clear because I was showing 2 different things?

```
const regex = XRegExp('(?<x>a)(?<y>b\\w+)', 'i');
const regexG = XRegExp.globalize(regex);
const str = 'jabba the hut is ABout 300 lbs.';
console.log(str);

let m = null;
while (m = regexG.exec(str)) {
    console.log(`m[0] = '${m[0]}'; m.x = ${m.x}; m[1] = ${m[1]}; m.y = ${m.y}; m[2] = ${m[2]}`);
}
```

**Actual:**
HELLO WORLD!
jabba the hut is ABout 300 lbs.
m[0] = 'abba'; m.x = undefined; m[1] = a; m.y = undefined; m[2] = bba
m[0] = 'ABout'; m.x = undefined; m[1] = A; m.y = undefined; m[2] = Bout

My understanding was that globalize works like /regex/g in the default implementation and the whole point of 'g' + exec() is to get matches one by one, being able to stop when I want.  In my application I want to move lastIndex along and test each match with a 2nd regex, stopping when I succeed.

**_What am I missing?_**

**Comment by slevithan** [comment]
Yes, so, `XRegExp.exec` intentionally does not use the provided regex's `lastIndex` prop for the search start position. See <http://xregexp.com/api/#exec>. See also <http://blog.stevenlevithan.com/archives/fixing-javascript-regexp> for details about some of the challenges and complexities of `lastIndex` and `/g`.

When using XRegExp methods, you never need to rely on `/g` or `lastIndex`. `XRegExp.globalize` is there to help you out when working with non-XRegExp methods that rely on `/g` and `lastIndex`, often in subtle and confusing ways.

There are at least a couple ways to address this with XRegExp. One is to explicitly set the starting position with `XRegExp.exec`'s `pos` argument:

```
let pos = 0;
let m = null;
while (m = XRegExp.exec(str, regex, pos)) {
  console.log(...);
  pos = m.index + (m[0].length || 1);
}
```

In the above case, there's no need to globalize the regex. It will work exactly the same with or without `/g`, and regardless of the initial value of the regex's `lastIndex`. Also note that I'm explicitly incrementing `pos` by at least `1`, to support cases where the regex is capable of zero-length matches (you have to watch out for the same thing when using regexes in loops and not using XRegExp).

The second way is even easer:

```
XRegExp.forEach(str, regex, m => {
  console.log(...);
});
```
