### ISSUE TITLE
XRegExp.tag, function to take full advantage of tagged literals

### ISSUE THREAD

**Issue by GingerPlusPlus** [slevithan/xregexp#204]
Not a pull request, because I'm not familiar with the source code, structure and conventions of the project.

Take a look at [this well commented gist](https://gist.github.com/GingerPlusPlus/0bb228c6d43703d23ef5f675fd678992) to get the idea.

I use [slightly improved* version of it](https://github.com/GingerPlusPlus/Rextester-bot-v3/blob/35b988f/utils/string.js#L28-L38) in my own project.

<sup>* It's not yet perfect. Regexs' source should be wrapped in `nonCapturingGroup` as well.</sup>

It allows to use tagged template literals to create regexes to its fullest.

Using it looks a little unusual, but there needs to be a way to pass flags.

Improvements over `XRegExp()` and `XRegExp.build()`:

1. It dispatches to `String.raw`, so backslashes behave as in regex literals; it avoids the ["Regexes, strings, and backslashes" issue](http://xregexp.com/api/).
2. Interpolation is achieved via native syntax for interpolation.

The best name for this function I can come up with is `XRegExp.tag`.

@josephfrazier mentioned `XRegExp.tag` in #195. I haven't seen it mentioned in docs, is it a thing already?

**Comment by josephfrazier** [comment]
[`XRegExp.tag`](https://github.com/slevithan/xregexp/blob/a661cd3ebbaf9950f947c5b92039d7c565ce8a5b/src/addons/build.js#L75-L103) is present on the master branch, but I don't think there's been a release including it. It uses `XRegExp.build`, so I'm not sure if it behaves the same way as your implementation.

**Comment by GingerPlusPlus** [comment]
Thanks for reply and link to the function, @josephfrazier.

> I'm not sure if it behaves the same way as your implementation.

If `XRegExp.build` wraps the substitutions in non-capturing group (the code's too long to check that quickly), then the implementation in repo should behave the same way, maybe `XRegExp.build` takes care of some cases I haven't encountered.

I find it funny how I called usage of my version "a little unusual", and then I see a function doing the same with the exact same signature :). Turns out it is _the_ way.

> I don't think there's been a release including it.

Yeah... just checked.

There hasn't been any activity in the repo and releases on npm since months... and all those unhandled issues and PRs...

Is the repo abandoned? If so, do you know any fork which is maintained?

**Comment by josephfrazier** [comment]
> If XRegExp.build wraps the substitutions in non-capturing group (the code's too long to check that quickly), then the implementation in repo should behave the same way

I'm pretty sure it does. From the comments in the code linked above: "Interpolated patterns are treated as atomic units when quantified". Here's [the relevant test](https://github.com/slevithan/xregexp/blob/a661cd3ebbaf9950f947c5b92039d7c565ce8a5b/tests/spec/s-addons-build.js#L26-L32).

> I find it funny how I called usage of my version "a little unusual", and then I see a function doing the same with the exact same signature :). Turns out it is the way.

Haha, great minds think alike! Another way to do it would be to require the template literal to start/end with a `/`, but allow flags to be after the final `/`. This could be a little more readable, but it's more complicated to implement.

> There hasn't been any activity in the repo and releases on npm since months... and all those unhandled issues and PRs...
> 
> Is the repo abandoned? If so, do you know any fork which is maintained?

According to http://forked.yannick.io/slevithan/xregexp, @GerHobbelt has a fork at https://github.com/GerHobbelt/xregexp that was updated 2 months ago. I don't know anything further about it, though.

I'm not sure if anyone other than @slevithan has commit/publish permissions for this repo/package, but maybe we could convince them to add me or another contributor as a maintainer, in order to keep things moving forward.

**Comment by slevithan** [comment]
> I'm not sure if anyone other than @slevithan has commit/publish permissions for this repo/package, but maybe we could convince them to add me or another contributor as a maintainer, in order to keep things moving forward.

It's just me and @mathiasbynens. I've gone ahead and given you push access to the repo, @josephfrazier. Please be careful. :)

**Comment by josephfrazier** [comment]
Hey @GingerPlusPlus, just wanted to let you know that v4.0.0 has been published and it includes `XRegExp.tag`. See https://github.com/slevithan/xregexp/pull/205 for context.

**Comment by GingerPlusPlus** [comment]
> maybe XRegExp.build takes care of some cases I haven't encountered.

This is one case I haven't considered:

> any backreferences within an interpolated regex are rewritten to work within the overall pattern.
