### ISSUE TITLE
any way to retrieve captured groups without knowing their names?

### ISSUE THREAD

**Issue by horacimacias** [slevithan/xregexp#209]
I'm using xregexp and I'm trying to iterate through the matched captured groups.
Is there any way to do this? I tried iterating through all properties of the match results but I can see other properties (e.g. 'input', 'index', 'length').

Is there any way to getting only the names of the captured groups? or names+values?

**Comment by josephfrazier** [comment]
I think this is a duplicate of https://github.com/slevithan/xregexp/issues/45. Please see there for some workarounds.

**Comment by slevithan** [comment]
#175 is tracking the proposal to improve this.

**Comment by horacimacias** [comment]
ah thanks. sorry I didn't see that other issue.
