### ISSUE TITLE
Upgrade to Unicode 10

### ISSUE THREAD

**Issue by slevithan** [slevithan/xregexp#215]
The data for XRegExp's Unicode plugins currently uses Unicode 9.0.0.

**Comment by slevithan** [comment]
See #171 for upgrade steps.

**Comment by josephfrazier** [comment]
https://github.com/slevithan/xregexp/issues/171#issuecomment-293201412:

> It might be worth considering rewriting the build scripts to consume the node-unicode-data packages, e.g. https://github.com/mathiasbynens/unicode-9.0.0, directly. This would greatly simplify things and could reduce the manual work required for such updates in the future.

I might be interested in taking this approach, if it's ok with you. I'd probably start by rewriting the existing script to use `unicode-9.0.0` and make sure that the tests pass and that the built files are equivalent, then I would upgrade to `unicode-10.0.0`.

**Comment by slevithan** [comment]
That sounds fantastic!

**Comment by mathiasbynens** [comment]
@josephfrazier Yes please! Go for it, and feel free to ping me if you run into any issues.
