### ISSUE TITLE
Add xregexp-all.js in the root repo

### ISSUE THREAD

**Issue by fedorenko-dmitriy** [slevithan/xregexp#216]
Hi. Can you add xregexp-all.js in the repo root as it was in the previous versions?

**Comment by josephfrazier** [comment]
Hi @fedorenko-dmitriy, can you describe your use case a bit more? `xregexp-all.js` was removed for the reasons described in https://github.com/slevithan/xregexp/pull/182#issuecomment-297190156, but I hope we can find an alternative that doesn't break your workflow.

**Comment by fedorenko-dmitriy** [comment]
I load your lib through the bower and bower get it from the git repo. After update version to 4.0.0. I get next message

Running "karma:phantom" (karma) task
PhantomJS 2.1.1 (Linux 0.0.0) ERROR LOG: 'There is no timestamp for /base/src/bower_components/xregexp/xregexp-all.js!'
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
http://requirejs.org/docs/errors.html#scripterror
  at node_modules/requirejs/require.js:143

**Comment by josephfrazier** [comment]
Unfortunately, XRegExp no longer supports installation via Bower, as described in the link from my previous message. You can load `xregexp-all.js` from https://unpkg.com/xregexp@4.0.0/xregexp-all.js, or switch to npm/yarn instead of bower.

**Comment by fedorenko-dmitriy** [comment]
Thank you for quick answer

**Comment by josephfrazier** [comment]
You're welcome! I'm going to go ahead and close this, but let me know if you have any more questions.
