### ISSUE TITLE
ERROR TypeError: xregexp_all_js_1.XRegExp is not a function in Angular5.x

### ISSUE THREAD

**Issue by ashishpatel0720** [slevithan/xregexp#218]
I am using angular5 for creating simple application for regex testing, but I am getting following error when try to create instance using the following syntax,
![image](https://user-images.githubusercontent.com/16856802/36074933-01d5cfac-0f6d-11e8-82b5-ff6f4c3a8d8d.png)

this works fine when I use simple it inside **jsfiddle** or **jsbin**, I am not able to figure out what happening,
this is my component typescript file,
![image](https://user-images.githubusercontent.com/16856802/36074995-c73ed2c0-0f6d-11e8-9550-e41d10a88495.png)

this is my **package.json**
![image](https://user-images.githubusercontent.com/16856802/36074975-94291508-0f6d-11e8-9fa3-ff26dab93fa7.png)

**Comment by slevithan** [comment]
Try using `import XRegExp from "xregexp";`

Note that the meaning of `import {name} from "module"` and `import name from "module"` are different. XRegExp only uses a default export, and the exported function doesn't include "XRegExp" as a property. `import * as name from "module"` is also equivalent in this case. The documentation for JavaScript's import and export statements on MDN might be helpful to understand this.

Another thing: You can remove the two occurrences of `\n\` you have in your regex, since you are using template literals with `` `...` `` to create a multiline string.

**Comment by ashishpatel0720** [comment]
@slevithan thanks for fast reply

**Comment by ashishpatel0720** [comment]
**I am getting following error when i am using as you said,**
![image](https://user-images.githubusercontent.com/16856802/36083849-798bdcce-0fdd-11e8-896e-f7475174cbc7.png)
**I am able to use it using a CDN, but when i want to use through NPM , i get an error**
![image](https://user-images.githubusercontent.com/16856802/36084084-b88e9fea-0fdf-11e8-8074-441b51b3f7de.png)

**Comment by josephfrazier** [comment]
Hmm, it seems like your build tool may not be properly finding the exported values. It looks like you're using angular, so I made a codesandbox that demonstrates the issue. It looks like using `const XRegExp = require("xregexp");
` works instead.

https://codesandbox.io/s/xp3421x64q (see the bottom of /main.ts, and open the console to see the logs)

**Comment by ashishpatel0720** [comment]
`import XRegExp from 'xregexp';`  **is not working but**
`import * as XRegExp from 'xregexp';` **is working just fine**

it think it has something to do with **tsconfig.json**

anyway thanks @slevithan @josephfrazier for help.

**Comment by josephfrazier** [comment]
Thanks for the confirmation, @ashishpatel0720, I'm glad you found a solution!

**Comment by RFMV34** [comment]
Can you help me, how to import it? I still get 
`
depends on 'xregexp'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

`
