### ISSUE TITLE
How do you do interpolation

### ISSUE THREAD

**Issue by iongion** [slevithan/xregexp#229]
I am using xregexp for a minimalistic router, I have the need to build reverse urls.
If my regexp is `'/program-tools/(?<section>\\d+)/(?<tool>.*)$'`, I would like to call something that passing a scope, will replace the scope parameters(same name as named capture groups), like this:

```
re.interpolate({ section: 23, tool: 'my-nice-tool' }
// should output `/program-tools/23/my-nice-tool`
```

**Comment by josephfrazier** [comment]
Hmm, I'm not sure if XRegExp can directly help with this use case. [XRegExp.build](http://xregexp.com/api/#build) is related, but different. If your named groups don't contain `)` characters, you could probably construct a regular expression that matches `(?<section>\\d+)` and `(?<tool>.*)`, and replaces them with the corresponding value from `{ section: 23, tool: 'my-nice-tool' }`.

As I was typing the above, I got curious and decided to throw something together:

```js
'/program-tools/(?<section>\\d+)/(?<tool>.*)$'.replace(/\(\?\<([^>]*)\>[^)]*\)/g, (match, p1) => ({ section: 23, tool: 'my-nice-tool' })[p1])
// => '/program-tools/23/my-nice-tool$'
```

---

If your use case is more demanding, you'll probably need a proper regexp parser like https://github.com/DmitrySoshnikov/regexp-tree

**Comment by iongion** [comment]
@josephfrazier Thank you, it totally makes sense!

**Comment by josephfrazier** [comment]
I just came across a solution for routes like `/user/:id`, thought I'd post it here since it's related: https://github.com/pillarjs/path-to-regexp/tree/761c721f9516d2739f87af3d303f5c096d1159d9#compile-reverse-path-to-regexp
