### ISSUE TITLE
Replicate perls \G flag

### ISSUE THREAD

**Issue by JaredCE** [slevithan/xregexp#231]
Would it be possible to replicate perl's \G flag? see about half way down here: https://perldoc.perl.org/perlretut.html#Using-regular-expressions-in-Perl.

**Comment by josephfrazier** [comment]
My initial impression is that this would be pretty complicated to support in XRegExp, especially if we wanted to support the use case in the link, which involves multiple distinct regular expressions, where one uses `/g` and the other uses `\G`. However, you might be able to implement similar behavior yourself by checking [the `lastIndex` property](https://devdocs.io/javascript/global_objects/regexp/lastindex) of the first regex, then setting the `lastIndex` of the second regex to equal it before matching the string again.

**Comment by JaredCE** [comment]
Hey, sorry for the late reply. you're right, using the 'y' flag and lastIndex, i can kind of replicate the \G flag.  cheers for pointing me in the right direction.
