### ISSUE TITLE
Thai seems to not work correctly

### ISSUE THREAD

**Issue by rihadavid** [slevithan/xregexp#232]
I have this test:

    //GOAL: allow letters of all languages, numbers, spaces, some basic symbols. do not allow special characters (e.g. heart) or emojis
    var unicodeWord = XRegExp("^[\\s\\p{L}\\p{N}_.:?!;+%@,()-]+$");
    var ok = unicodeWord.test("ช้างเก่า"); //translated "old elephant" in google translator, returns false

I tried Cyrillic, Chinese, Arabic, those work fine, except for the Thai symbols.
Am I doing something wrong or is there an issue? I see in the `xregexp-all.js` that Thai is defined, so where is the problem?
Thanks

**Comment by slevithan** [comment]
The non-spacing mark U+0E49 occurs twice in your subject string, which is what your regex is failing to match. If you use ``XRegExp.tag()`^[\p{L}\p{Mn}]+$` `` as your regex instead, it will work. You could also use ``XRegExp.tag()`^\p{Thai}+$` ``.
