### ISSUE TITLE
Can you get match.index for a /.../g regex?

### ISSUE THREAD

**Issue by working-name** [slevithan/xregexp#233]
Hello there, how do I get to any match.index if I run a `/.../g` regex for example? I tried every way I could think of, but can't get it to spit it out. Is that not a feature?

**Comment by josephfrazier** [comment]
Can you describe what you've tried? It looks like this works:

```js
const XRegExp = require('xregexp');
XRegExp(/bar/g).exec('foobar').index; // 3
```
