### ISSUE TITLE
Named variable not working for me v4.1.1

### ISSUE THREAD

**Issue by davvyy00** [slevithan/xregexp#235]
` let error = {}, validLowToHigh, arrayKms = []
    if(this.hasLetters(text)){
      error.errors = true
      error.errorMsg = ValidationConstants.HAS_LETTERS_ERROR
      errorData.push(error)
    }

    validLowToHigh = XRegExp(`(?<kmHigh> [0-9]+)  -?  #capture the first set of digit
                              (?:\\-|\\s)         -?  #let the user have a - or a space between digits
                              (?<kmLow> [0-9]+)       #capture the second set of the digits`,'x')
    if(validLowToHigh.test('100-200')){
      arrayKms = validLowToHigh.exec(text,validLowToHigh)
    }

  }`

**Comment by slevithan** [comment]
You need to use `XRegExp.exec`, rather than `<regexp>.exec` to get back named captures. It used to be possible to do this using `XRegExp.install('natives')`, but support for that was removed in XRegExp v4.0.0.
