### ISSUE TITLE
toString and newline escaping

### ISSUE THREAD

**Issue by bd82** [slevithan/xregexp#244]
```javascript
> xregExp.build("\n").toString()
'/\n/' // not escaped.

> /\n/.toString()
'/\\n/' // escaped
```

I saw #70 but I'm not sure if its the same issue.
Is xRegExp supposed to behave differently than the native regExp here?

**Comment by slevithan** [comment]
Your examples here are not equivalent, so it’s not correct to say they are behaving differently. You are passing a literal line feed character (with a string length of 1) into `XRegExp.build`, which is different from the 2 character pattern in your regex literal.

**Comment by bd82** [comment]
I am not sure I understand.
I think both the regExps constructed are **semantically** identical
and that they match a **single** newline character.

inside a regExp literal "\n" is a [controlEscape](https://www.ecma-international.org/ecma-262/8.0/index.html#prod-ControlEscape) 

```javascript
> /\n/.test("\n") // would false if the pattern tested was 2 characters long.
true
> xregExp.build("\n").test("\n")
true
> 
```

Am I missing something here?

**Comment by slevithan** [comment]
> inside a regExp literal "\n" is a controlEscape

No it’s not. It is a pattern that _matches_ a line feed character, but a regex literal is not a string. Strings have their own character escaping rules. Thus `/\n/` and `RegExp(“\\n”)` are equivalent.

**Comment by bd82** [comment]
Thanks I understand now.
