### ISSUE TITLE
regex don't work in node less then 10

### ISSUE THREAD

**Issue by riazXrazor** [slevithan/xregexp#250]
Hi, 
i am having a weired issue, 

```
my Regex
(?<start>classs*=s*["\'].*?)(?<given>(?<![-_.wd])col\\-md\\-1(?![-_.wd]))(?<end>.*?["\'])
```

```
SyntaxError: Invalid regular expression: 
/(classs*=s*["'].*?)((?<![-_.wd])container\-fluid(?![-_.wd]))(.*?["'])/: 
Invalid group
```
whenever i try to run it on node lower then 10 it gives error.
i am kind of helpless.

**Comment by LoganDark** [comment]
Can't you just run it on 10?

**Comment by slevithan** [comment]
You are using negative lookbehind via `(?<!`. Lookbehind assertions are a feature of ES 2018, and XRegExp relies on native support for them to work (e.g. this is still not supported in the latest Firefox).
