### ISSUE TITLE
Problem in Firefox

### ISSUE THREAD

**Issue by jeaneric** [slevithan/xregexp#251]
I have this xregexp that fails in Firefox 60.0.2. It works in chrome and node.
var a=xregexp(`(?<![!<>=])[=](?![<>=])`)

Giving message: SyntaxError: invalid regexp group.
Run this and look at the console: https://codepen.io/anon/pen/wXdjBR

Solved my problem using another expression.

**Comment by slevithan** [comment]
Firefox does not yet support RegExp lookbehind assertions, which were only introduced in the ES 2018 standard. This is an issue with the native regular expressions that XRegExp is compiling down to. XRegExp does not provide non-native support for lookbehind.
