### ISSUE TITLE
Use without native regex object?

### ISSUE THREAD

**Issue by LoganDark** [slevithan/xregexp#252]
I'm looking to port a regex engine to a language that doesn't currently have one. XRegExp uses native JavaScript regexes. Is it possible to support avoiding these?

**Comment by josephfrazier** [comment]
Not easily, and it isn't really the scope of this project to re-implement a regex engine. I'm curious: what language are you working with?

**Comment by LoganDark** [comment]
Nope. The language is sandboxed Lua - e.g. ROBLOX or Minecraft. This issue is basically closed with a "no" because of your comment on #250:

> XRegExp relies on native support

**Comment by josephfrazier** [comment]
Ah, I see. I take it that Lua's native regex syntax is either insufficient or unavailable in that environment? I searched around a bit and found https://github.com/pygy/LuLPeg, which might be helpful. Looks like it was written by one of the XRegExp contributors, too (@pygy)!

**Comment by LoganDark** [comment]
@josephfrazier sandboxed = no native code.

**Comment by LoganDark** [comment]
That is not regex at all.

**Comment by josephfrazier** [comment]
Oh well, it was worth a try, I guess. Good luck!
