### ISSUE TITLE
Minified files missing from v2.0.0 when installed via npm

### ISSUE THREAD

**Issue by bighappyface** [slevithan/xregexp#256]
When installing XRegExp v2.0.0 via `npm` the `min` directory is missing:

```shell
$ mkdir wtf
$ cd wtf/
$ npm init
# Add "xregexp": "^2.0.0" to dependencies
$ npm i
npm WARN package.json wtf@1.0.0 No description
npm WARN package.json wtf@1.0.0 No repository field.
npm WARN package.json wtf@1.0.0 No README data
xregexp@2.0.0 node_modules/xregexp
$ ls node_modules/xregexp/
MIT-LICENSE.txt	README.md	package.json	tests		xregexp-all.js
```

**Comment by josephfrazier** [comment]
Hey @bighappyface, sorry for the crazy delay here! v2.0.0 is pretty old (7 years). Are you able to upgrade?

**Comment by bighappyface** [comment]
@josephfrazier thanks for getting back to me. Sure, I can upgrade, but the fact is that files have gone missing from a previous, published version. Upgrading isn't the issue, and I am concerned that files going missing from any version would mean files could go missing from... any version. Upgrading doesn't save me from files vanishing.

Regardless, I am closing.

**Comment by josephfrazier** [comment]
Hmmm, you're saying the files have disappeared from the NPM-hosted version? That seems pretty unlikely, but I suppose it's possible. At any rate, if that's the case, it sounds like something to take up with NPM. All we could possibly do is publish a `v2.0.1`, but I don't know if it's a good idea to continue supporting v2 anyway...

**Comment by mathiasbynens** [comment]
They haven’t disappeared; they were never there.

```
$ npm i xregexp@2.0.0

$ cat node_modules/xregexp/.npmignore
min/
src/
tests/index.html
tests/qunit/
tools/
```

I’m not sure what the bug is here.

**Comment by josephfrazier** [comment]
Thanks for the report, and I'm glad to hear it worked out (assuming you don't have difficulties upgrading)!
