### ISSUE TITLE
\pL unicode category is removing accents when used with replace on Russian words

### ISSUE THREAD

**Issue by cdmckay** [slevithan/xregexp#257]
If I try to make a regex to remove all non-letter characters, it removes accents:
```
var str = 'Росси́йскаяФедера́ция';
var regexp = XRegExp('[^\\pL]+', 'gu');
var result = XRegExp.replace(str, regexp, '');
document.writeln(result); // === РоссийскаяФедерация (notice the и and а is missing an accent)
document.writeln(result === str); // === false
```

The expected behaviour in this case is that the `str` would be unmodified.

Here's the JSFiddle
https://jsfiddle.net/vpq4ocur/1/

**Comment by slevithan** [comment]
Sounds like you should include `\pM` in your regex along with `\pL`.

**Comment by cdmckay** [comment]
Ah, I see, thanks!
