### ISSUE TITLE
Exception on React Native 

### ISSUE THREAD

**Issue by lorenc-tomasz** [slevithan/xregexp#259]
> undefined is not a function (evaluating 'optionalFlags[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
> addToken
>     xregexp.js:760:28
> <unknown>
>     xregexp.js:2000:17
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     index.js:8:45
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     usernameValidator.js:2
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     ProfileHomeScreen.js:24
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     HomeStackNavigator.js:8
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     App.js:46
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:214:36
> metroRequire
>     require.js:136:24
> <unknown>
>     index.android.js:3
> loadModuleImplementation
>     require.js:320:6
> guardedLoadModule
>     require.js:207:45
> metroRequire
>     require.js:136:24
> global code
>     
> 

With 3.2.0 everything works ok

**Comment by ducaale** [comment]
version 4.1.1 also works

**Comment by josephfrazier** [comment]
@slevithan, it looks like this might be due to the use of `Symbol`, which also caused problems in https://github.com/slevithan/xregexp/issues/254, and was fixed after version `4.2.0`. Should we release version `4.2.1` and see if it helps?

**Comment by josephfrazier** [comment]
Great, I'll put together the PR

**Comment by lorenc-tomasz** [comment]
4.2.2:

`Unable to resolve module `@babel/runtime/core-js/get-iterator` from `/Projects/xyz/node_modules/xregexp/lib/addons/unicode-base.js`: Module `@babel/runtime/core-js/get-iterator` does not exist in the Haste module map`

**Comment by josephfrazier** [comment]
See https://github.com/slevithan/xregexp/issues/262

**Comment by slevithan** [comment]
@lorenc-tomasz can you confirm whether this is resolved in v4.2.4?

**Comment by lorenc-tomasz** [comment]
@slevithan Bug resolved in 4.2.4. Thanks.
