### ISSUE TITLE
xregexp capture all groups and pos for each match

### ISSUE THREAD

**Issue by mafar** [slevithan/xregexp#267]
I created an issue here @[stackoverflow](https://stackoverflow.com/questions/54994546/js-regexp-capture-all-groups-and-pos-for-each-match)

Is it possible to get a result similar to https://regex101.com by using xregexp
where one is able to see full match , groups and matched string postion as well
regex https://regex101.com/r/HZ7O0l/1
try fiddle  https://jsfiddle.net/bababalcksheep/o4qn7jwe/6/

**Comment by klesun** [comment]
Please answer, your lib is our only hope!

**Comment by klesun** [comment]
Apparently it's not possible with this lib, since it uses buil-in js implementation for execution, a bummer:
https://github.com/slevithan/xregexp/issues/217
