### ISSUE TITLE
XRegExp.replaceRecursive

### ISSUE THREAD

**Issue by tdjastrzebski** [slevithan/xregexp#274]
Is there any way to achieve functionality similar to string.replace() from XRegExp.matchRecursive?
E.g. XRegExp.replaceRecursive(str, left, right, flags, replacer: (match:string) => string)

The problem is XRegExp.matchRecursive() returns string[] and does not provide information about where exactly match was found within the string to make a replacement.

**Comment by slevithan** [comment]
Yes! It is possible to write a function that does this. You’ll need to use `XRegExp.matchRecursive`’s `valueNames`  option, which has advanced capabilities but is a bit complicated. There are examples of using this included as comments in the file, and at <xregexp.com/api/#matchRecursive>. When using the `valueNames` option, all returned string parts will include `start` and `end` integer values that give the match start and end positions within the subject string.

**Comment by tdjastrzebski** [comment]
I see. To get matches only should I use: `valueNames: [null, null, 'match', null]`, rather than just `['match']`? In the second case I actually get 'between' values. I am slightly confused.

**Comment by slevithan** [comment]
Yes, that's correct about providing 3 null values to skip the parts you don't want returned. (Or a more complex solution would be to name those other parts as well, and then skip over any returned objects whose name property's value is not 'match'.) This API provides a lot of flexibility but is not very intuitive or natural to use. I'd be happy to see matchRecursive improved in the future.

**Comment by slevithan** [comment]
Adding a built in replaceRecursive function might be a nice improvement as well. But I'd probably first want to clean up the matchRecursive API.

**Comment by tdjastrzebski** [comment]
Thanks. I think it would be good to include typescript definitions as well. The one available via npm has incorrect return value:
`function matchRecursive(str: string, left: string, right: string, flags?: string, options?: Object): string[];`

**Comment by slevithan** [comment]
Pull requests are welcome. 😀

**Comment by tdjastrzebski** [comment]
In case someone needs recursive replace (typescript syntax).

```
const XRegExp = require('xregexp');
interface M { start: number; end: number; value: string; }

function replaceRecursive(text: string, left: string, right: string, replacer: (match: string) => string): string {
	var r: M[] = XRegExp.matchRecursive(text, left, right, 'g', { valueNames: [null, null, 'match', null] });
	var offset: number = 0;
	for (const m of r) {
		const replacement = replacer(m.value);
		text = replaceAt(text, m.start + offset, m.value.length, replacement);
		offset += replacement.length - m.value.length;
	}
	return text;
}

function replaceAt(string: string, index: number, length: number, replacement: string): string {
	return string.substr(0, index) + replacement + string.substr(index + length);
}
```

**Comment by tdjastrzebski** [comment]
@slevithan here is more complete solution I developed and successfully use

```
const XRegExp = require('xregexp');

export interface XRegExpPart { start: number; end: number; name: string; value: string; }
export interface XRegExpMatch { index: number; outerText: string; innerText: string; left: string; right: string; }

export function replaceRecursive(text: string, left: string, right: string, replacer: (match: XRegExpMatch) => string, options: string = 'g'): string {
	const matches: XRegExpMatch[] = matchRecursive(text, left, right, options);
	let offset: number = 0;

	for (const match of matches) {
		const replacement = replacer(match);
		if (replacement == match.outerText) continue;
		text = replaceAt(text, match.index + offset, match.outerText.length, replacement);
		offset += replacement.length - match.outerText.length;
	}
	return text;
}

export function matchRecursive(text: string, left: string, right: string, options: string = 'g'): XRegExpMatch[] {
	// see: https://github.com/slevithan/xregexp#xregexpmatchrecursive
	const parts: XRegExpPart[] = XRegExp.matchRecursive(text, left, right, options, { valueNames: [null, 'left', 'match', 'right'] });
	const matches: XRegExpMatch[] = [];
	let leftPart: XRegExpPart;
	let matchPart: XRegExpPart;

	for (const part of parts) {
		// note: assumption is made that left, match and right parts occur in this sequence
		switch (part.name) {
			case 'left':
				leftPart = part;
				break;
			case 'match':
				matchPart = part;
				break;
			case 'right':
				matches.push({ index: leftPart!.start, innerText: matchPart!.value, outerText: leftPart!.value + matchPart!.value + part.value, left: leftPart!.value, right: part.value });
				break;
			default:
				throw new Error(`Unexpected part name: '${part.name}'.`);
		}
	}

	return matches;
}

export function replaceAt(string: string, index: number, length: number, replacement: string): string {
	return string.substr(0, index) + replacement + string.substr(index + length);
}
```

**Comment by slevithan** [comment]
Cool, thanks for sharing it here 👍
