### ISSUE TITLE
Cannot supply flags when copying a RegExp (ver 4.2.4)

### ISSUE THREAD

**Issue by tdjastrzebski** [slevithan/xregexp#276]
Trying to pass left/right delimiters as RegExp, rather than strings
```
const str1 = '(t((e))s)t()(ing)';
const s = XRegExp.matchRecursive(str1, /\(/, /\)/);
const t = XRegExp.matchRecursive(str1, /\(/g, /\)/g);
```
I get:
```
TypeError: Cannot supply flags when copying a RegExp
    at XRegExp ([...]\node_modules\xregexp\lib\xregexp.js:591:13)
```
Am I missing something?

**Comment by josephfrazier** [comment]
According to the documentation at http://xregexp.com/api/#matchRecursive, flags must be supplied separately, and the left/right delimiters must be String patterns, not RegExp literals. Try this instead:

```js
var XRegExp = require("xregexp")

const str1 = '(t((e))s)t()(ing)';
const s = XRegExp.matchRecursive(str1, '\\(', '\\)');
const t = XRegExp.matchRecursive(str1, '\\(', '\\)', 'g');
```

For example: https://runkit.com/embed/xn0xcrzjp4s0

**Comment by tdjastrzebski** [comment]
Thanks, I was looking at some very old version where this method seemed to allow for RegEx arguments.
