### ISSUE TITLE
Dependency on core-js@2 which is no longer maintend

### ISSUE THREAD

**Issue by humphreyn** [slevithan/xregexp#279]
Hi,
Currently xregexp has a dependency on @babel/runtime-corejs@2 and in turn has a dependency on core-js@2 which according to the developers "is no longer maintained and not recommended for usage due to the number of issues".

Do you have plans to upgrade to @babel/runtime-corejs@3 which uses core-js@3.

**Comment by tdjastrzebski** [comment]
This becomes a real issue. Not to mention **core-js** runs postinstall script displaying info about the author looking for a job...
![core-js](https://user-images.githubusercontent.com/7325277/73250904-217f4c00-41b8-11ea-8ae8-0d0f3a07df23.png)
