### ISSUE TITLE
Some Bengali unicode characters reported as invalid

### ISSUE THREAD

**Issue by tscislo** [slevithan/xregexp#291]
I'm testing against for example: কি using v 4.3.0 and result is:
```
const unicodeWord = XRegExp('^\\pL+$');
unicodeWord.test('কি'); //-> false, but it should be true
```
This happens for some bengali characters

**Comment by slevithan** [comment]
Your test string `'কি'` contains 2 code points:

- U+0995
  - BENGALI LETTER KA
  - Category: Letter, Other [Lo]
- U+09BF
  - BENGALI VOWEL SIGN I
  - Category: Mark, Spacing Combining [Mc]

What I'd recommend is to include combining marks in your allowed word characters, like so:

```js
const unicodeWord = XRegExp('^[\\pL\\p{Mc}]+$');
unicodeWord.test('কি'); //-> true
```

**Comment by tscislo** [comment]
Thanks that helped!
