### ISSUE TITLE
Feature request: Character set from string array

### ISSUE THREAD

**Issue by miloshavlicek** [slevithan/xregexp#292]
**Feature request (for discussion):**
It would be useful to be able to create a new character set from a string array of allowed chars.

At this time I have my own static function that escapes and joins chars from string array, however, I think it can be useful also for others.

**Example implementation:**
``` typescript
const matchingChars = ['a','e','i','o','u', '+'];
const result = [];
const re = XRegExp(`${XRegExp.charsetFromArray(matchingChars)}+`); // expected translation: [aeiou\+]+
while (match = XRegExp.exec('heeeja+aola', re)) {
    result.push(match);
}
// expected output: ['eee', 'a+ao', 'a']
```

**Comment by slevithan** [comment]
How about:

```js
const chars = 'aeiou+'; // or: ['a','e','i','o','u','+'].join('');
const re = XRegExp('[' + XRegExp.escape(chars) + ']+');
const result = XRegExp.match('heeeja+aola', re, 'all'); // ['eee','a+ao','a']
```

If it wasn’t for the bug described in #192 (where interpolation isn’t currently allowed inside character classes), you could replace the second line with ``const re = XRegExp.tag()`[${chars}]+`;``.

**Comment by mathiasbynens** [comment]
Note that for usage with plain JS regular expressions (i.e. without XRegExp), [regenerate](https://github.com/mathiasbynens/regenerate) solves this problem. Given a set of characters, it produces a valid & ASCII-safe JS regular expression pattern that matches only those characters.

```js
regenerate('a','e','i','o','u', '+').toString();
// --> '[\\+aeiou]'
```

https://repl.it/repls/BackThirstySoftwareengineer
