### ISSUE TITLE
Can we have some position information in Unbalanced delimiter error?

### ISSUE THREAD

**Issue by 3cp** [slevithan/xregexp#293]
Related to #96 

I wonder is it possible to add position information to the error message?

```
Unbalanced delimiter found in string
    at Function.XRegExp.matchRecursive (node_modules/xregexp/lib/addons/matchrecursive.js:211:15)
```

Something like
```
Unbalanced delimiter found in string, for left delimiter at position 123
```

So that it's easier for user to find out where is the problem in the input string.

**Comment by slevithan** [comment]
Great suggestion! PRs welcome. :)
