### ISSUE TITLE
Implement ES6 export file

### ISSUE THREAD

**Issue by BorisZubchenko** [slevithan/xregexp#297]
It would be great if we could import `xregexp` with ES6 import statement. More info [here](https://github.com/apollographql/graphql-tag/issues/303)

Angular 10 prints the following error during build process:
```
WARNING in XXX depends on 'xregexp'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by josephfrazier** [comment]
This sounds like it may be related to https://github.com/slevithan/xregexp/issues/218#issuecomment-364961229, where a workaround was found. Maybe that will work for you?

**Comment by BorisZubchenko** [comment]
I have no `is not a function` error but a warning during build process. The build may work but the warning annoys (and it can really `cause optimization bailouts`).

**Comment by josephfrazier** [comment]
Oh, I think I see now. We actually do have [a `module` field in `package.json`](https://github.com/slevithan/xregexp/pull/281/files), but I don't think it's in a released version. You might be to import from `xregexp/src/index.js` as a workaround, until this change gets released.

**Comment by josephfrazier** [comment]
A version with `module` has been released by now, so I'm going to close this.
