### ISSUE TITLE
how would i go about finding out what this does?  (the 27 is just my favorite number below...)  

### ISSUE THREAD

**Issue by cellurl3** [slevithan/xregexp#302]
XRegExp('^(.{'+27+'}(?:\\p{L}|[\'’](?=\\p{L}))*)(.*)', 's')

thanks for any tools,tips...

Newbie Jim

**Comment by josephfrazier** [comment]
Your best bet is probably to paste the pattern (`^(.{'+27+'}(?:\p{L}|'’))(.)`) into https://regexr.com/ or another website that explains regular expressions. You might also want to take a regex tutorial to (re) familiarize yourself with the concepts. Here's one I just found by searching for `regex tutorial`: https://blog.usejournal.com/regular-expressions-a-complete-beginners-tutorial-c7327b9fd8eb
