### ISSUE TITLE
Error: Unbalanced delimiter found in string

### ISSUE THREAD

**Issue by vyushin** [slevithan/xregexp#307]
XRegExp version: 4.4.0

I'm trying provide string with double quotes to `matchRecursive` method

```javascript
const str = '"Hello, "World"!"';
XRegExp.matchRecursive(str, '"', '"', 'g');
```

this throws an error:

```bash
Error: Unbalanced delimiter found in string
```

The same case works with other symbols. For example:

```javascript
const str = '{"hello": { "value": "world" }}';
XRegExp.matchRecursive(str, '{', '}', 'g') // Ok
```

How can I use matchRecursive to find matches in string containing double quotes?

**Comment by slevithan** [comment]
`XRegExp.matchRecursive` in its current form doesn't work with identical left and right delimiters. That said, you can adapt your task so the positions your delimiters match are not identical with something like this:

```js
const str = '"Hello, "World"!"';
XRegExp.matchRecursive(str, '"(?=\\w)', '"(?!\\w)', 'g');
// -> ['Hello, "World"!']
```
