### ISSUE TITLE
Issue with flags

### ISSUE THREAD

**Issue by john5634** [slevithan/xregexp#313]
Hello! I am using XRegExp to deal with an old version of firefox that our javascript tool must work with. The version of firefox does not allow s (dotall) and negative look behinds. 

I tried to use XRegExp to solve that issue, but it seems it does not keep the "s" flag when generating a regex object from a string. 

Regex I used was /<CD>.*?<\/CD>/gms (g for global, m for multiline, s for dotall)

With the text of:  
"<CD>Hello</CD>
<CD>Hello2</CD>
<LP>Hello3</LP>"

Should result in 2 matches match0 = "<CD>Hello</CD>"
and match1 = "<CD>Hello2</CD>"

But for some reason it doesent! the regex generated when I print the regex object removes the s flag!!!

Why would it remove the s flag?

Again I am using XRegExp to deal with an old version of Firefox that I must use. any version of Firefox before version 50 will show the results for sure!

**Comment by slevithan** [comment]
The `s` flag won't show up, but the generated regex will behave like the `s` flag is present.

```js
XRegExp('.').test('\n'); // false
XRegExp('.', 's').test('\n'); // true

var regex = XRegExp('.', 's');
regex.xregexp.flags; // 's'
```
