### ISSUE TITLE
Positive lookbehinds not working

### ISSUE THREAD

**Issue by john5634** [slevithan/xregexp#314]
Hello!

Trying to use positive lookbehinds with XRegExp and it does not seem to work.

Is this known?

TRYING TO MATCH: "Empire Burlesque"

WITH:

REGEX:
(?<=<TITLE>)(.*)(?=</TITLE>)

STRING:
<CD>
<TITLE>Empire Burlesque</TITLE>
<ARTIST>Bob Dylan</ARTIST>
<COUNTRY>USA</COUNTRY>
<COMPANY>Columbia</COMPANY>
<PRICE>10.90</PRICE>
<YEAR>1985</YEAR>
</CD>

**Comment by slevithan** [comment]
What browser are you testing it with? Lookbehind should work if and only if you're using a browser / JavaScript runtime that supports regex lookbehind natively.

**Comment by john5634** [comment]
We are suing firefox 67. Which does not support Lookbehinds. We were hoping that XRegExp would enable them?

**Comment by slevithan** [comment]
No, lookbehind is not something XRegExp provides on its own.

For your regex and example string, it seems simple enough to use a regex like this instead:

```js
/<TITLE>(.*?)</TITLE>/
```

Then just reference the value in capturing group 1, rather than the whole match.
