### ISSUE TITLE
Change "types" to "types/index.d.ts" in package.json

### ISSUE THREAD

**Issue by AaronBeaudoin** [slevithan/xregexp#324]
Basically, the line in `package.json` where the types path is specified does not align with TypeScript's official documentation for [publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) because it points to a _directory_ and not a _file_. This cases VS Code to display the following error in the standard jsconfig.json file at the root of a project's directory:

![image](https://user-images.githubusercontent.com/26592486/111220451-3202a980-85a7-11eb-8099-c0fb8937bfaa.png)

See [this](https://stackoverflow.com/questions/63124462/how-to-fix-file-node-modules-dotenv-types-not-found-error-coming-from-j) StackOverflow thread for more information.

**Comment by josephfrazier** [comment]
Thanks for the report, @AaronBeaudoin, and for linking the stackoverflow thread. Would you mind opening a PR with the desired change?
