### ISSUE TITLE
The ChainArrayElement type was incorrectly defined

### ISSUE THREAD

**Issue by bawangxx** [slevithan/xregexp#325]
`

interface ChainArrayElement {
       
        regexp: RegExp;

        backref: number | string;
 }

`

Should be changed to
`

interface ChainArrayElement {
      
        regex: RegExp;
       
        backref: number | string;
    }

`

Property regex has an extra p

When used in TypeScript, it returns an error

[![screen](https://note.youdao.com/yws/public/resource/35bc5fde0078e7496aeb5352a08f7d01/xmlnote/DC5B059005634F148B50E4741E49409D/2954)](https://github.com/bawangxx/xz_voice)

[![screen](https://note.youdao.com/yws/public/resource/35bc5fde0078e7496aeb5352a08f7d01/xmlnote/EE99492706C6462C9B1F95908705E971/2956)](https://github.com/bawangxx/xz_voice)

"xregexp": "^4.4.1"

Thank you for providing such an excellent and powerful framework

**Comment by slevithan** [comment]
Thanks for the report! Fixed.

**Comment by slevithan** [comment]
Fix released in v5.0.2.
