### ISSUE TITLE
Wrong example code

### ISSUE THREAD

**Issue by h-h-h-h** [slevithan/xregexp#344]
Link: https://xregexp.com/api/#exec

Wrong code:

```
// Basic use, with named backreference
let match = XRegExp.exec('U+2620', XRegExp('U\\+(?[0-9A-F]{4})'));
match.groups.hex; // -> '2620'

// With pos and sticky, in a loop
let pos = 2, result = [], match;
while (match = XRegExp.exec('<1><2><3><4>5<6>', /<(\d)>/, pos, 'sticky')) {
  result.push(match[1]);
  pos = match.index + match[0].length;
}
// result -> ['2', '3', '4']
```

Correct code (changed lines bold and italic):

<pre>
// Basic use, with named backreference
<b><i>let match = XRegExp.exec('U+2620', XRegExp('U\\+(?&lt;hex>[0-9A-F]{4})'));</i></b>
match.groups.hex; // -> '2620'

// With pos and sticky, in a loop
<b><i>let pos = 3, result = [], match;</i></b>
while (match = XRegExp.exec('&lt;1>&lt;2>&lt;3>&lt;4>5&lt;6>', /&lt;(\d)>/, pos, 'sticky')) {
  result.push(match[1]);
  pos = match.index + match[0].length;
}
// result -> ['2', '3', '4']
</pre>

When [searching](https://github.com/search?q=Basic+use+with+named+backreference+repo%3Aslevithan%2Fxregexp&type=Code) for it in the repo, there were multiple similar occurrences. So, I don't know where to change it.

But in the search results I already saw `(?<hex>`. I just had the same problem while writing this markdown, the problem that `<hex>` was hidden when I wrote:

    <pre>
    // Basic use, with named backreference
    <b><i>let match = XRegExp.exec('U+2620', XRegExp('U\\+(?<hex>[0-9A-F]{4})'));</i></b>

I solved it by using `&lt;`. So, for you, it may also have to do with `<hex>` being interpreted as an HTML tag.

And don't forget the incorrect starting position.

**Comment by slevithan** [comment]
Oof. Thanks for catching and reporting that. I'll fix it in all relevant locations.

**Comment by slevithan** [comment]
xregexp.com has been updated with the documentation fix.
