### ISSUE TITLE
What does (?xn) and (?x) mean in the following? 

### ISSUE THREAD

**Issue by st-clair-clarke** [slevithan/xregexp#353]
```
lib.preexponent = XRegExp.build('(?xn)\
lib.exponent = XRegExp.build('(?x)\....

```

I saw them at [https://blog.stevenlevithan.com/archives/grammatical-patterns-xregexp-build](https://blog.stevenlevithan.com/archives/grammatical-patterns-xregexp-build)

Thanks

**Comment by slevithan** [comment]
They are mode modifiers. See <https://xregexp.com/syntax/#modeModifier>.

`(?xn)` enables two flags: `x` and `n`, and `(?x)` enables just the `x` flag.

See <https://xregexp.com/flags/> for details about these flags.

**Comment by st-clair-clarke** [comment]
Great. Thank you.
