### ISSUE TITLE
Question; I cannot get a group to be captured

### ISSUE THREAD

**Issue by st-clair-clarke** [slevithan/xregexp#356]
Hi
I am attempting to understand the [Reformat Names with Particle](https://read.amazon.com/?asin=B008Y4OP1O&ref_=kwl_kr_iv_rec_1)

The regex copied from the book is 

```^(.+?)●((?:(?:d[eu]|l[ae]|Ste?\.?|v[ao]n)●)*[^\s,]+)↵ (,?●(?:[JS]r\.?|III?|IV))?$```
My corresponding conversion to XRegExp attempt is

```
export const reformatNameWithParticleRegex = (): RegExp => XRegExp.tag('nxi')`
 ^  (?<firstAndMiddle> .+?)
    (?<last>
      (?<particle> (d[eu]|l[ae]|Ste?\.?|v[ao]n ))
      *[^\s,]+
    )
    (?<suffix> ,? (?:[JS]r\.?|III?|IV))?$`

```

**My usage is:**

```
export const reformatNameWithParticle = (subject: string) => {
  const nameMatchParticle = XRegExp.exec( subject, reformatNameWithParticleRegex() )
  
  if( isNil( nameMatchParticle) ){
    return `No match found for entry ${subject}`
  }
  
  console.log({nameMatchParticle})
  
  const [input, firstAndMiddle, last, particle, suffix] = nameMatchParticle
  const formatted = `${particle} ${last ?? ''}, ${firstAndMiddle} ${suffix ?? ''}`
  return XRegExp.replace(subject, reformatNameWithParticleRegex(), trim(formatted))
}


    const namePart = reformatNameWithParticle('Charles de Gaulle')
   const namePart1 = reformatNameWithParticle('John F Kennedy')
  console.log({namePart, namePart1})
```

Observe my console result:

![image](https://github.com/slevithan/xregexp/assets/3227590/ed6a8308-0ab1-4156-9d33-3cc53ae6ac28)

Note the undefined array items at indices 3, and 4 are undefined.

Thanks for your help.

**Comment by st-clair-clarke** [comment]
A big thank you.

After copying your example, it did not work for me simply because my IDE optimised the '\ ' on save => hence null was return. However, after replacing the '\ ' with '\x20' it worked.

**Comment by slevithan** [comment]
`\x20` is a good solution, and probably what I would use. Another option is `[ ]` since XRegExp treats whitespace inside character classes as meaningful even when using flag `x`.
