### ISSUE TITLE
Question: Is there a repository for the examples in the 'Regular Expression Cookbook'

### ISSUE THREAD

**Issue by st-clair-clarke** [slevithan/xregexp#357]
I am having an issue about the book. I purchased it in Kindle. But, as you know, I cannot copy Kindle because of the DRM.

While it is not too bad to type the small examples, but with the larger ones it is rather tedious.

Is there a repository with the examples, maybe in text format for us to copy/paste as we progress through the book?

**Comment by slevithan** [comment]
You can find them here for copying and pasting: https://www.regular-expressions-cookbook.com/

PS It's better not to use the XRegExp repo as a place for questions specifically about _Regular Expressions Cookbook_ since it is an entirely independent project.
