### ISSUE TITLE
Unicode support for \b revisited

### ISSUE THREAD

**Issue by mgoldenbe** [slevithan/xregexp#361]
The closed Issue #228 discussed this some 6 years ago. Is `\b` supported for Unicode at this point? 
It is not working in my test:
![image](https://github.com/slevithan/xregexp/assets/24386790/7c73af12-2bc7-4079-ae2d-a8225e8a139a)

**Comment by slevithan** [comment]
Closing to merge into #228 where you've posted your test code.
