### ISSUE TITLE
XRegExp fails under Rhino

### ISSUE THREAD

**Issue by jaquet9** [slevithan/xregexp#46]
I am trying to use XRegExp 3.0.0-pre with Rhino 1.6r2 (which is the version of Rhino shipping with Java 6). 

Compiling the regex below (taken from http://xregexp.com/ ):

```js
date = XRegExp('(?<year>  [0-9]{4} ) -?  # year  \n' +
               '(?<month> [0-9]{2} ) -?  # month \n' +
               '(?<day>   [0-9]{2} )     # day     ', 'x');
```

triggers the following error message: 

```
"Invalid quantifier ?" at script line 517 (which is the line: "return augment(new RegExp(key.pattern, key.flags), key.captures, /*addProto*/ true);")
```

Inspecting `key.pattern` reveals that the `?<...>` are not being stripped out:

```
(?<year>(?:)[0-9]{4}(?:))(?:)-?(?:)year(?:)(?<month>(?:)[0-9]{2}(?:))(?:)-?(?:)month(?:)(?<day>(?:)[0-9]{2}(?:))(?:)day
```

Does anyone have a workaround?

**Comment by slevithan** [comment]
@jaquet9, sorry for the long delay. Is it possible to verify whether this is still occurring with the latest versions of XRegExp 3.0.0-pre and Rhino (currently Rhino 1.7.6)? Thanks!

**Comment by slevithan** [comment]
Will reopen if anyone is able to verify whether this is still failing in Rhino.
