### ISSUE TITLE
Support for (?-i) mode modifiers in the middle of the regex?

### ISSUE THREAD

**Issue by bdom200** [slevithan/xregexp#69]
Any plans on supporting negative and positive mode modifiers (?letters), such as (?i) and (?-i), in the middle of the regex? 

For example: Input : (?i)te(?-i)st 
                      Matches: test, TEst, but not teST or TEST.

http://www.regular-expressions.info/refmodifiers.html 

Thanks!

**Comment by slevithan** [comment]
https://github.com/mikesamuel/regexp-make-js seems to allow building case sensitive regexes using embedded case-insensitive regexes. Haven't looked into what edge cases it might have though, and whether / how well it supports Unicode.
