### ISSUE TITLE
Could you please update xregexp on npm and bower to 3.0

### ISSUE THREAD

**Issue by andyhu** [slevithan/xregexp#78]
Thanks!

**Comment by EgoAleSum** [comment]
+1
The workaround works but every time you run "npm update" it re-downloads everything. 3.0 seems pretty stable to me.

**Comment by riquito** [comment]
In the meanwhile do not use the master's tarball, use a fixed commit hash, it will download the data only once.

e.g. in bower

    "dependencies": {
        "xregexp": "slevithan/xregexp#2650989f9a"
    }

**Comment by slevithan** [comment]
Thanks for all the interest and support. There are some as-yet-incomplete backward incompatible changes I'm planning to make for 3.0, which is why I've been reluctant to update it until getting back into the project. The release of Unicode 8.0 final soon might be a good time for this.

**Comment by gajus** [comment]
[Unicode 8.0.0](https://www.npmjs.com/package/unicode-8.0.0) has been released now.

**Comment by slevithan** [comment]
Yup! A number of improvements have been made since last commenting here, and XRegExp v3.0.0 is finally nearing release. Want to make a couple final tweaks to support ES6 regex changes and update the Unicode data, and it will ready.

**Comment by slevithan** [comment]
XRegExp 3.0.0 final was released on GitHub and npm a week ago now. Will register on Bower shortly.
