### ISSUE TITLE
AMD, CommonJS, UMD

### ISSUE THREAD

**Issue by iongion** [slevithan/xregexp#80]
Just a nice to have, although ugly, it is very useful, more info at:

[UMD Project](https://github.com/umdjs/umd)

**Comment by slevithan** [comment]
XRegExp already supports RequireJS, CommonJS, and Node.js module systems, and provides a global variable for direct use in <script> tags. What's remaining that you think is useful? See https://github.com/slevithan/xregexp/blob/master/tools/intro.js

**Comment by slevithan** [comment]
Can reopen if more details are provided. Would be happy to see a pull request that showed what changes would be helpful.
