### ISSUE TITLE
Splitting advise

### ISSUE THREAD

**Issue by alan-haziq** [slevithan/xregexp#82]
Hi.

I need help with regexp expression.

XRegExp.matchChain(text, [XRegExp("[\\p{Alphabetic}\\p{Nd}\\{Pc}\\p{M}]+", "g")]

For text "læseWEB læser teksten på dit website op.", I get ["læseWEB", "læser", "teksten", "på", "dit", "website", "op"]

How can I get ["læseWEB ", "læser ", "teksten ", "på ", "dit ", "website ", "op."]?

**Comment by lydell** [comment]
`"læseWEB læser teksten på dit website op.".match(/\S+\s*/g)`
