### ISSUE TITLE
Can't install the "extensibility" 

### ISSUE THREAD

**Issue by pulupulu01** [slevithan/xregexp#84]
Help me plz~  

--------------My Running enviroment----------------
Server:    Windows 7 x64 + Apache 2.4 + PHP V5.5
Browser:  Chrome 39

--------------My code------------------
console.info(XRegExp.isInstalled('natives'));
console.info(XRegExp.isInstalled('extensibility'));
XRegExp.install('natives');
XRegExp.install('extensibility');
console.info(XRegExp.isInstalled('natives'));
console.info(XRegExp.isInstalled('extensibility'));

----------------results in chrome console---------------------
false
false
true
false

Did I miss anything? Thanks!

**Comment by slevithan** [comment]
If you are using XRegExp v3.0.0-pre (the version here on GitHub), the 'extensibility' feature no longer exists. It's functionality is now always on, and doesn't need to be tested for or installed.
