### ISSUE TITLE
V2.0.0 Minified missing closing semi-colon

### ISSUE THREAD

**Issue by shmuel613** [slevithan/xregexp#87]
the v2.0.0 minified versions (xregexp-min.js and xregexp-all-min.js) are missing a closing semi-colon in their respective files.

**Comment by slevithan** [comment]
Hm, I will be careful to ensure there is a closing semi-colon in future "official" minified versions. But not sure I should attempt to change the past on this for V2.0 on CDNs etc.

**Comment by shmuel613** [comment]
Thanks! XRegExp is an awesome library, btw.  Thanks for putting it out
there.
