### ISSUE TITLE
partial installation on node

### ISSUE THREAD

**Issue by tresdin** [slevithan/xregexp#88]
I use `XRegExp` for testing unicode letters. Basically, I just want to include these 3 files `xregexp.js`, `unicode-base.js` and `unicode-categories.js` on both node side and browsers side. Unfortunately, I still need to install the full package via npm to be able to use `XRegExP` on node instead of `require('/path/to/xregexp.js')`.

**Comment by slevithan** [comment]
Would be happy to see pull requests that showed how this would work.

**Comment by slevithan** [comment]
This was made possible in XRegExp 3.1.0. You can now require just the addons you need on the Node side. See how this is done in `src/index.js`. Doing this for browsers no longer has a prebuilt solution, but you can create exactly the bundle you want for browsers by creating an equivalent of `src/index.js` with fewer addons included and then bundling it using Browserify's `--standalone` option (`browserify my-package.js --standalone XRegExp > xregexp-plus-unicode-categories.js`).

Would be happy to see any improvements that make this easier for browsers.

**Comment by tresdin** [comment]
I personally think sooner or later, `xregexp` will need to support partial installations on both `nodejs` and browsers via a single command. May be something similar to this command in my situation:
```
//install
npm install @categories/xregexp
//usage
let XRegExp = require('@categories/xregexp');
```
The above command should install `xregexp` with just these 3 files  `xregexp.js`, `unicode-base.js` and `unicode-categories.js` then bundle them into a single file located on `xregexp` root folder (or any other locations). Its path should be stored within the `XRegExp` object (`XRegExp.bundledScriptPath` or `XRegExp.constants.bundledScriptPath` for example).

This approach also makes it much easier to be updated or deleted via `npm`.
