### ISSUE TITLE
Combining min folder and src folder

### ISSUE THREAD

**Issue by Piicksarn** [slevithan/xregexp#92]
Hi~
Is it possible to make min folder and src folder combine into dist folder?
This would enable wider distribution of the library, for example on [CDNJS](https://github.com/cdnjs/cdnjs). 
And thanks for your great work!!!

Piiksarn

**Comment by slevithan** [comment]
I'm not opposed to it, but not sure I understand the benefit. It seems both minified and non-minified copies of XRegExp are already on CDNJS.

**Comment by slevithan** [comment]
The need for a `dist` folder would be clearer if all the scripts in `src` had to run through a build script before being ready for distribution/use, but that's not the case today so most of what's in `dist` would just be copies of `src`. If it seems appropriate to you or others, I could rename `src` to `scripts` to make it clearer that what's in there can be used as is.

Maybe `dist` could be added with minified copies of everything in `src` plus `xregexp-all.js`, and running all these files through UglifyJS or similar could be added to the `build` script in `package.json`. I'm not very familiar with conventions around directory structures and build steps in typical projects like this. Would be happy to see a pull request that set up better structure and build steps around this stuff.

**Comment by slevithan** [comment]
Closing since the latest release (v3.1.0) doesn't include a `min` folder. Would still be happy to see pull requests that improve build steps or organization.
