### ISSUE TITLE
Match Unicode String

### ISSUE THREAD

**Issue by nehakadam** [slevithan/xregexp#93]
Hi Steven,

This is not actually an issue, just a query.

I want to detect a date pattern for that I have written a Regex which works for English but does not work for Russian language using javascript `RegExp`, since Javascript does not support unicode characters.

**English**
Date Pattern :  "Aug 09,2015"
Regex :  `/(\[[^\[]*\])|(\\)?(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)(\b \b)(\d{1,2})(\b,\b)(\d{1,4})|./g`

**Russian**
Date Pattern: "авг 09,2015"
Regex : `/(\[[^\[]*\])|(\\)?(янв|фев|март|апр|май|июнь|июль|авг|сен|окт|ноя|дек)(\b \b)(\d{1,2})(\b,\b)(\d{1,4})|./g`

How to write 
`/(\[[^\[]*\])|(\\)?(янв|фев|март|апр|май|июнь|июль|авг|сен|окт|ноя|дек)(\b \b)(\d{1,2})(\b,\b)(\d{1,4})|./g` 
with XRegExp `\p{Letter}`?

Thank You.

**Comment by boughtonp** [comment]
I'd guess it's because `\b` doesn't know about unicode letters (i.e. it's only for boundaries with `[0-9A-Za-z_]`), and unless I'm missing something they're redundant anyway, so replace `(\b \b)` and `(\b,\b)` with just `( )` and `(,)` respectively.

**Comment by nehakadam** [comment]
Hey, Thanks Peter. It is working now.
