### ISSUE TITLE
Can't install version 3.0.0

### ISSUE THREAD

**Issue by tresdin** [slevithan/xregexp#94]
I've tried installing `XRegExp` via this command `npm install xregexp`. Then version `2.0.0` was installed instead of `3.0.0`.

*P/s. I'm using iojs v3.0.0*.

**Comment by boughtonp** [comment]
Did you check the existing issues before posting? If so, you missed both https://github.com/slevithan/xregexp/issues/63 and https://github.com/slevithan/xregexp/issues/78...
