### ISSUE TITLE
Unicode searching

### ISSUE THREAD

**Issue by georgeslegros** [slevithan/xregexp#95]
Hello,

I'm trying to see if this library can help me. I have a list of user and multiple of those have accents and other diacritics in their names (Loïc, ...).
I was using the string.search passing the search text and "i" as a second parameter before I found out that it does not play nice with Unicode...

Do you know if it is possible to use the test method of this library to find if I have a match?

**Comment by slevithan** [comment]
Can you give a more specific example of the code for the search you are attempting?

**Comment by georgeslegros** [comment]
So I have an array of names like this: ["Georges", "Loïc", "Albert"]
I'm trying to search on the array from a search text. 
Loïc has a screwed up i with 2 dots on it.
When people are searching for it they type "Loic"

So I am looking for the syntax to use in XRegExp to kind of ignore the diacritics (not only those 2 dots but all diacritics) so I can use the test method. It should also ignore the case ("i").

Do you think that this is possible?

For information I solved the problem by removing the diacritics from both search text and array values with a piece of code found here: http://web.archive.org/web/20120918093154/http://lehelk.com/2011/05/06/script-to-remove-diacritics/

However I find this nasty and I if possible I'd like to get back to XRegExp.

Thanks,

**Comment by slevithan** [comment]
Sorry, XRegExp isn't able to help with that. Not only does the base library not have anything built in for that, but XRegExp's Unicode data also doesn't have information that might assist.
