### ISSUE TITLE
Update Unicode data to v8.0

### ISSUE THREAD

**Issue by slevithan** [slevithan/xregexp#97]

**Comment by slevithan** [comment]
Closed by commits https://github.com/slevithan/xregexp/commit/4c98f2fc2e7edcfd22db07ebc5faa53e6781efc6, https://github.com/slevithan/xregexp/commit/5ddb1283991e5d6e0b405af7e45cff2dfb74d2c5, https://github.com/slevithan/xregexp/commit/940232b282ad179acfba3adbdf5fbe038fe9d590, https://github.com/slevithan/xregexp/commit/6c21be582594be6ffbbc99cc416b0de525550e0f.

**Comment by slevithan** [comment]
Thanks @mathiasbynens for making this so easy with the great scripts you set up!

**Comment by mathiasbynens** [comment]
:+1:
